<a href="https://colab.research.google.com/github/Armandot1998/Pyton-Jupyter-Notebook/blob/master/Clase1IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch; 

In [6]:
torch.__version__

'1.6.0+cu101'

In [7]:
# funcion ones sirve para llenar un tensor
tensor_a = torch.ones(4, 4);
tensor_a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
tensor_p = torch.ones(3, 3);
print(tensor_p);

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [9]:
# tensor != tensor ==> datos aleatorios en un tensor
tensor_b = torch.Tensor(3, 3);
tensor_b

tensor([[2.2309e-35, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3733e-14, 6.4069e+02, 4.3066e+21]])

In [10]:
tensor_1 = torch.Tensor(4, 4);
tensor_1

tensor([[2.2309e-35, 0.0000e+00, 1.2612e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [11]:
# .uniform --> limita en uso dedatos a usar (max / min)
tensor_b = torch.Tensor(4, 4);
print(tensor_b);
tensor_b.uniform_(0, 1);

tensor([[2.2309e-35, 0.0000e+00, 2.2421e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [12]:
print(tensor_1);
tensor_1.uniform_(0, 1);

tensor([[2.2309e-35, 0.0000e+00, 1.2612e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [13]:
# .rand --> numeros aleatorios entre 0 y 1
tensor_c = torch.rand(3, 3);
tensor_c

tensor([[0.3935, 0.2063, 0.4747],
        [0.7012, 0.1046, 0.5110],
        [0.3229, 0.3645, 0.8218]])

In [14]:
tensor_2 = torch.rand(4, 4);
tensor_2

tensor([[0.3557, 0.9509, 0.9560, 0.1895],
        [0.6581, 0.0943, 0.8215, 0.3000],
        [0.2315, 0.4024, 0.5607, 0.1361],
        [0.9844, 0.6962, 0.3433, 0.3900]])

In [15]:
# las operaciones con tensores se pueden realizar siempre y cuando sean matematicamente correctas
result = tensor_a + tensor_b
result

tensor([[1.4053, 1.0643, 1.7002, 1.1793],
        [1.7292, 1.9217, 1.3235, 1.5652],
        [1.5755, 1.2736, 1.1655, 1.9351],
        [1.7835, 1.8550, 1.8781, 1.0872]])

In [16]:
result2 = tensor_a - tensor_b
result2

tensor([[0.5947, 0.9357, 0.2998, 0.8207],
        [0.2708, 0.0783, 0.6765, 0.4348],
        [0.4245, 0.7264, 0.8345, 0.0649],
        [0.2165, 0.1450, 0.1219, 0.9128]])

In [17]:
# shape --> las dimensiones del tensor
# .view --> transforma un tensor en caso de ser posible

result.shape
print(result.shape);
resshaped = result.view (1, 16);
print(resshaped);
deresult = result.view(16, 1);
print(deresult);

torch.Size([4, 4])
tensor([[1.4053, 1.0643, 1.7002, 1.1793, 1.7292, 1.9217, 1.3235, 1.5652, 1.5755,
         1.2736, 1.1655, 1.9351, 1.7835, 1.8550, 1.8781, 1.0872]])
tensor([[1.4053],
        [1.0643],
        [1.7002],
        [1.1793],
        [1.7292],
        [1.9217],
        [1.3235],
        [1.5652],
        [1.5755],
        [1.2736],
        [1.1655],
        [1.9351],
        [1.7835],
        [1.8550],
        [1.8781],
        [1.0872]])


In [18]:
result2.shape
print(result2.shape);
resshaped = result2.view (1, 16);
print(resshaped);
deresult = result2.view(16, 1);
print(deresult);

torch.Size([4, 4])
tensor([[0.5947, 0.9357, 0.2998, 0.8207, 0.2708, 0.0783, 0.6765, 0.4348, 0.4245,
         0.7264, 0.8345, 0.0649, 0.2165, 0.1450, 0.1219, 0.9128]])
tensor([[0.5947],
        [0.9357],
        [0.2998],
        [0.8207],
        [0.2708],
        [0.0783],
        [0.6765],
        [0.4348],
        [0.4245],
        [0.7264],
        [0.8345],
        [0.0649],
        [0.2165],
        [0.1450],
        [0.1219],
        [0.9128]])


In [19]:
#.tensor --> da la capacidad de poner los datos en un tensor en base a lo que un autor desea o necesite.
tensor_d = torch.tensor([[1.0, 2.0], [3.4, 4.6], [1.1, 6.3], [2.1, 6.5]])
print(tensor_d);

# para llamar un dato especifico se lo llama en base a su ubicacion
# en el tensor como si se trataese de una matriz. De la misma manera se lo pude modificar.
print(tensor_d [0] [1]);
tensor_d [0] [1] = 4.7
print(tensor_d);

# .storage() --> La manera en que especificamente se guarda un espacio de memoria.
tensor_d.storage();

tensor([[1.0000, 2.0000],
        [3.4000, 4.6000],
        [1.1000, 6.3000],
        [2.1000, 6.5000]])
tensor(2.)
tensor([[1.0000, 4.7000],
        [3.4000, 4.6000],
        [1.1000, 6.3000],
        [2.1000, 6.5000]])


In [20]:
tensor_3 = torch.tensor([[1.0, 2.0, 3.3], [3.4, 4.6, 6.6], [1.1, 6.3, 5.5], [2.1, 6.5, 4.5]])
print(tensor_3);

print(tensor_d [0] [1]);
tensor_3 [0] [1] = 4.7
print(tensor_3);

tensor_3.storage();

tensor([[1.0000, 2.0000, 3.3000],
        [3.4000, 4.6000, 6.6000],
        [1.1000, 6.3000, 5.5000],
        [2.1000, 6.5000, 4.5000]])
tensor(4.7000)
tensor([[1.0000, 4.7000, 3.3000],
        [3.4000, 4.6000, 6.6000],
        [1.1000, 6.3000, 5.5000],
        [2.1000, 6.5000, 4.5000]])


In [21]:
# .stride --> se refiere a como se pude mover de una serie de datos a la otra en base a las dimensiones del tensor

"""la idea del stride es poder acceder al elemento de manera fisica en memoria,
mas que del simple hecho de accederlo logicamente(por ejemplo point[0][1] ). y es ahi donde stride me dice como hacerlo.
 """
print(tensor_d, tensor_d.stride());


tensor([[1.0000, 4.7000],
        [3.4000, 4.6000],
        [1.1000, 6.3000],
        [2.1000, 6.5000]]) (2, 1)


In [22]:
print(tensor_3, tensor_3.stride());

tensor([[1.0000, 4.7000, 3.3000],
        [3.4000, 4.6000, 6.6000],
        [1.1000, 6.3000, 5.5000],
        [2.1000, 6.5000, 4.5000]]) (3, 1)


In [23]:
# .t --> transpuesta de un tensor
transpuesta = tensor_d.t();
print(transpuesta, transpuesta.stride());

tensor([[1.0000, 3.4000, 1.1000, 2.1000],
        [4.7000, 4.6000, 6.3000, 6.5000]]) (1, 2)


In [24]:
transpuesta = tensor_3.t();
print(transpuesta, transpuesta.stride());

tensor([[1.0000, 3.4000, 1.1000, 2.1000],
        [4.7000, 4.6000, 6.3000, 6.5000],
        [3.3000, 6.6000, 5.5000, 4.5000]]) (1, 3)


In [25]:
# .unsqueese --> agrega una dimension a un tensor en caso de ser necesario
tensor_x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]);
print(tensor_x), torch.unsqueeze(tensor_x, 1)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


(None, tensor([[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11],
         [12],
         [13],
         [14]]))

In [26]:
# biblioteca para el procesamiento de datos en ML, principalmente numericos
import numpy as np

In [27]:


# cambio de un array np a un tensor torch

numpayArray = np.random.randn(4, 4);
torch.from_numpy(numpayArray);
print(numpayArray)

[[-0.9121034  -0.37324284 -0.02417181  0.68690566]
 [-1.24151641 -0.48830838  0.58157414  1.45321795]
 [ 0.74064683 -0.82868588  1.10897364 -0.3338142 ]
 [ 0.69983606 -0.14968185  1.06502188  0.41916078]]


In [28]:
numpayArray = np.random.randn(5, 5);
torch.from_numpy(numpayArray);
print(numpayArray)

[[-0.19321285 -0.98801314  0.17253104  1.80944018  1.51505198]
 [-0.6458024  -0.70084236  0.82595685  0.77687201  0.59979213]
 [-0.51523297 -0.27571154 -1.51669638  0.12121215  0.25134947]
 [ 0.19704537  1.91545101 -0.54168933 -0.75918664  0.07813021]
 [-0.42011871 -0.72804763 -0.89096749 -2.01046885 -2.44301212]]


In [33]:
nuevoArray = np.random.randn(4,4)
from_numpy = torch.from_numpy(nuevoArray)
print(from_numpy)

tensor([[ 0.6240,  1.6824, -1.7546,  0.7887],
        [ 0.9776,  0.1363, -0.6348, -0.0461],
        [-0.8434,  0.8558, -0.9931, -0.0286],
        [ 0.6951,  0.1123,  0.0828, -0.4125]], dtype=torch.float64)


REPRESENTAR DATOS CON TENSORES


In [39]:
# torch.mean --> media de un tensor
print(torch.mean(from_numpy))
tensor_4 = torch.Tensor([[1.7, 2.4, 4.5, 6.0, 3.5], [1.7, 2.4, 4.5, 6.0, 3.5], [1.7, 2.4, 4.5, 6.0, 3.5],[1.7, 2.4, 4.5, 6.0, 3.5], [1.7, 2.4, 4.5, 6.0, 3.5]])
print(tensor_4)

# dim --> implica la dimension en la cual se va calcular la media
print(torch.mean(tensor_4, dim=0))
print(torch.mean(tensor_4, dim=1))

print(torch.mean(tensor_4, dim=-1))
print(torch.mean(tensor_4, dim=-2))

tensor(0.0776, dtype=torch.float64)
tensor([[1.7000, 2.4000, 4.5000, 6.0000, 3.5000],
        [1.7000, 2.4000, 4.5000, 6.0000, 3.5000],
        [1.7000, 2.4000, 4.5000, 6.0000, 3.5000],
        [1.7000, 2.4000, 4.5000, 6.0000, 3.5000],
        [1.7000, 2.4000, 4.5000, 6.0000, 3.5000]])
tensor([1.7000, 2.4000, 4.5000, 6.0000, 3.5000])
tensor([3.6200, 3.6200, 3.6200, 3.6200, 3.6200])
tensor([3.6200, 3.6200, 3.6200, 3.6200, 3.6200])
tensor([1.7000, 2.4000, 4.5000, 6.0000, 3.5000])


In [40]:
# torch.std --> la desviacion estandar de todo el tensor o solo en una de las dimensiones del mismo
print(torch.std(tensor_4, dim=0))
print(torch.std(tensor_4, dim=1))

print(torch.std(tensor_4, dim=-1))
print(torch.std(tensor_4, dim=-2))

tensor([0., 0., 0., 0., 0.])
tensor([1.7050, 1.7050, 1.7050, 1.7050, 1.7050])
tensor([1.7050, 1.7050, 1.7050, 1.7050, 1.7050])
tensor([0., 0., 0., 0., 0.])


In [41]:
# torch.save --> se usa para llamarlos en el Disco archivos/tensores para luego llamarlos
torch.save(tensor_4, 'tensor.t')

In [42]:
# torch.load --> se usa para llamar a los tensores guardados
load = torch.load('tensor.t')
load


tensor([[1.7000, 2.4000, 4.5000, 6.0000, 3.5000],
        [1.7000, 2.4000, 4.5000, 6.0000, 3.5000],
        [1.7000, 2.4000, 4.5000, 6.0000, 3.5000],
        [1.7000, 2.4000, 4.5000, 6.0000, 3.5000],
        [1.7000, 2.4000, 4.5000, 6.0000, 3.5000]])

In [43]:
# pandas es una biblioteca que nos ayuda a traer datasets y manejarlos de la mejor manera
import pandas as pd


In [50]:
# url nos deja importar un url desde algun lado para luego ultizarlo
# pd.read_cvs --> funcion de pandas para leer un archivo csv y dar disposicion de esos datos
url = 'http://ljz.gzd.mybluehost.me/ljz.gzd.mybluehost.me/players.csv'
dataframe = pd.read_csv(url) 
dataframe

match_id  ...  unit_order_continue
0              0  ...                  NaN
1              0  ...                  NaN
2              0  ...                  NaN
3              0  ...                  NaN
4              0  ...                  NaN
...          ...  ...                  ...
499995     49999  ...                  NaN
499996     49999  ...                  NaN
499997     49999  ...                  NaN
499998     49999  ...                  NaN
499999     49999  ...                  NaN

[500000 rows x 73 columns]

In [51]:
dataframe.columns

Index(['match_id', 'account_id', 'hero_id', 'player_slot', 'gold',
       'gold_spent', 'gold_per_min', 'xp_per_min', 'kills', 'deaths',
       'assists', 'denies', 'last_hits', 'stuns', 'hero_damage',
       'hero_healing', 'tower_damage', 'item_0', 'item_1', 'item_2', 'item_3',
       'item_4', 'item_5', 'level', 'leaver_status', 'xp_hero', 'xp_creep',
       'xp_roshan', 'xp_other', 'gold_other', 'gold_death', 'gold_buyback',
       'gold_abandon', 'gold_sell', 'gold_destroying_structure',
       'gold_killing_heros', 'gold_killing_creeps', 'gold_killing_roshan',
       'gold_killing_couriers', 'unit_order_none',
       'unit_order_move_to_position', 'unit_order_move_to_target',
       'unit_order_attack_move', 'unit_order_attack_target',
       'unit_order_cast_position', 'unit_order_cast_target',
       'unit_order_cast_target_tree', 'unit_order_cast_no_target',
       'unit_order_cast_toggle', 'unit_order_hold_position',
       'unit_order_train_ability', 'unit_order_drop_item',


In [97]:
# se puede armar una subseccion usando los corchetes, y llamandolos de un dataframe ya existente.
#los subsets = datframe [[hero_id, gold, kills, deaths, assists]]
# .dropna --> nos da la capacidad de eliminar ciertos tipos de columnas
subset = dataframe [[ 'kills', 'deaths', 'assists']].dropna(axis=0, how='any')

# se puede definir a travez de columns desde que columnas llamar despues. Exclusivos "Overall" porque no nos intereza explicarlo
columns = subset.columns [:]
print(columns)

# .float --> fuerza a los datos a ser fotantes para facilitar operaciones
players = torch.tensor(subset.values).float()
players.shape, players.type()


Index(['kills', 'deaths', 'assists'], dtype='object')


(torch.Size([500000, 3]), 'torch.FloatTensor')

In [91]:
# se puede eliminar una columna en especifico e este caso no eliminaremos ninguna
data = players[:, 2:]
data, data.shape

(tensor([[ 3., 18.],
         [ 3., 18.],
         [ 4., 15.],
         ...,
         [ 3., 11.],
         [ 6., 17.],
         [ 6., 17.]]), torch.Size([500000, 2]))

In [92]:
# se puede escoger una columna en concreto para tensor
target = players[:, 0]
target, target.shape

(tensor([3261., 2954.,  110.,  ..., 1059., 3165., 2972.]),
 torch.Size([500000]))

In [93]:
media = torch.mean(data, dim=0)
media

tensor([ 7.6808, 11.7619])

In [94]:
std = torch.std(data, dim=0)
std

tensor([3.8081, 6.3934])

In [95]:
# realizamos un proceso de noralizacion de datos en busqueda de z
normal = (data-media)/std
normal

tensor([[-1.2292,  0.9757],
        [-1.2292,  0.9757],
        [-0.9666,  0.5065],
        ...,
        [-1.2292, -0.1192],
        [-0.4414,  0.8193],
        [-0.4414,  0.8193]])

In [98]:
''' torch.get() --> ge = GreaterEqual (>=)
    torch.lt() --> lt = LowerThan (<)
    toch.gt() --> gt = GreaterTha (>)'''

    # creamos calsificaciones en base a los datos que tenemos

buenos = data[torch.ge(target, 85)]
normales = data[torch.gt(target, 70) & torch.lt(target, 85)]
regulares = data[torch.le(target, 70)]

    # creacion de medias de las cada clasificacion previamente creada

mbuenos = torch.mean(buenos, dim=0)
mnormales = torch.mean(normales, dim=0)
mregulares = torch.mean(regulares, dim=0)

columns, mbuenos, mnormales, mregulares

    

(Index(['kills', 'deaths', 'assists'], dtype='object'),
 tensor([ 7.6399, 11.9450]),
 tensor([9.3510, 9.0281]),
 tensor([8.4433, 7.4790]))