# Trabajo con Numpy

In [2]:
# Importamos la librería de Numpy
import numpy as np

# Consultamos la version que tenemos instalada 
print('numpy version: ', np.__version__)

numpy version:  1.18.1


In [3]:
# Declaramos un arreglo

a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])

# Con valores numéricos del 0 al 11 en cada fila

rows, cols = np.shape(a)

print ('Rows:{0:03d} ; cols:{0:03d}'.format(rows, cols))

print(a)

Rows:003 ; cols:003
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Agregando valores complejos

In [7]:
# Declaramos un arreglo con números naturales
# Pero los convertimos en numero complejos

b = np.array([[1, 2], [9, 0], [4, 5]], dtype = np.complex64)

print ('Rows:{0:03d} ; cols:{0:03d}'.format(rows, cols))

print(b)

Rows:003 ; cols:003
[[1.+0.j 2.+0.j]
 [9.+0.j 0.+0.j]
 [4.+0.j 5.+0.j]]


### Inicializar vectores de dimensión 

In [15]:
# Inicializando un vector con variables inciales de 0 
np.zeros((4, 4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# Devuelve una matriz de ceros con la misma forma y tipo que una matriz determinada. 
np.zeros_like(b)


array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]], dtype=complex64)

In [14]:
# Devuelve una nueva matriz de formas y tipos dados, sin inicializar entradas.
np.empty((3, 3))


array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 6.66e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [17]:
# Devuelve una matriz 2-D con unos en la diagonal y ceros en otro lugar.
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
# np.diag(): Se utiliza esta función para extraer una diagonal y desea escribir en la matriz resultante; 
# si devuelve una copia o una vista depende de qué versión de numpy esté usando.

# np.arange(): Devuelve valores espaciados uniformemente dentro de un intervalo dado.
x = np.arange(5)

np.diag(x)


array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [25]:
# Devuelve valores espaciados uniformemente dentro de un intervalo dado.
np.arange(5)


array([0, 1, 2, 3, 4])

In [31]:
# np.tile(): Construye una matriz repitiendo A el número de veces dado por repeticiones.
x = np.array([[1, 0], [0, 1]])

np.tile(x, (2, 2))


array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [38]:
# np.arage(): Devuelve valores espaciados uniformemente dentro de un intervalo dado.
# np.reshape(): Da una nueva forma a una matriz sin cambiar sus datos.
x = np.arange(9).reshape(3, 3)

print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [44]:
# No es necesario especificar los valores del vector uno a uno, ta,bien es posible generarlos
b = np.array([[10*j+i for i in range(3)] for j in range(4)])

print(b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [49]:
# Añadir una nueva dimensión o convertir un vector fila en column

# np.linspace(): Devuelve números espaciados uniformemente en un intervalo especificado
# calculadas a lo largo del intervalo [ inicio , detención ],
# el punto final del intervalo puede excluirse opcionalmente.

d = np.linspace(0, 15, 6)

print(d)

print(d[:, np.newaxis])

[ 0.  3.  6.  9. 12. 15.]
[[ 0.]
 [ 3.]
 [ 6.]
 [ 9.]
 [12.]
 [15.]]


In [50]:
# np.mgrid(): devuelve una malla de malla densa (o desarrollada) cuando se indexa,
# de modo que cada argumento devuelto tiene la misma forma. 
# Las dimensiones y el número de las matrices de salida son iguales al número de dimensiones de indexación. 
# Si la longitud del paso no es un número complejo, entonces la parada no es inclusiva.

x, y = np.mgrid[0:5, 0:5] 

print(x)

print("---")

print(y)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
---
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [57]:
from scipy import sparse

# np.random.random(): devuelve flotaciones aleatorias en el intervalo medio abierto [0.0, 1.0).
# Los resultados son de la distribución "uniforme continuo" durante el intervalo establecido.
# Para muestrear Unif [a, b), b> a, multiplique la salida de random_samplepor (ba) y agregue a
# ( b  -  a )  *  random_sample ()  +  a

x = np.random.random((5, 6))

x[x < 0.85] = 0

print(x)

x_csr = sparse.csr_matrix(x)

print(x_csr)

[[0.8794274  0.         0.         0.         0.         0.        ]
 [0.92523878 0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.98149701 0.901075   0.        ]
 [0.9577774  0.90323881 0.         0.         0.         0.        ]]
  (0, 0)	0.879427401022772
  (1, 0)	0.9252387771426219
  (3, 3)	0.9814970130117243
  (3, 4)	0.9010749973495815
  (4, 0)	0.9577774040855614
  (4, 1)	0.9032388059069186


In [59]:
# toarray(): convertirá en un arreglo definido la enterior expresión
print(x_csr.toarray())


[[0.8794274  0.         0.         0.         0.         0.        ]
 [0.92523878 0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.98149701 0.901075   0.        ]
 [0.9577774  0.90323881 0.         0.         0.         0.        ]]


In [60]:
# Numpy permite la generación de número aleatorios en base a una semilla previamente especificada 
np.random.seed(12345)

np.random.rand(4, 5)


array([[0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503],
       [0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987],
       [0.74771481, 0.96130674, 0.0083883 , 0.10644438, 0.29870371],
       [0.65641118, 0.80981255, 0.87217591, 0.9646476 , 0.72368535]])

In [64]:
np.random.randn(4, 4)

array([[ 1.34974221,  0.06987669,  0.24667411, -0.0118616 ],
       [ 1.00481159,  1.32719461, -0.91926156, -1.54910644],
       [ 0.0221846 ,  0.75836315, -0.66052433,  0.86258008],
       [-0.0100319 ,  0.05000936,  0.67021559,  0.85296503]])

In [67]:
# De la siguiente forma podemos hacer una tranformación del tipo de valor que se encuentra dentro del arreglo
a = np.array([1,7, 1.2, 1.6])

b = a.astype(int)

b

array([1, 7, 1, 1])

In [71]:
# Realizamos un aproximación a los valores tipo fload del arreglo a
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5, 4.5])

b = np.around(a)

c = np.around(a).astype(int)

# El resultado será mostrado con los valores con tipo de dato entero
print(c)

[1 2 2 2 4 4 4]


In [74]:
# importamos la array de numpy
from numpy import array

# Declaramos 2 arreglos diferente dentro de 2 variables
a = array([1.0, 2.0, 3.0])

b = array([2.0, 2.0, 2.0])

a = b

from numpy import array

a = array([[0.0, 0.0, 0.0,],
           [10.0, 10.0, 10.0],
           [20.0, 20.0, 20.0],
           [30.0, 30.0, 30.0]])

b = array([1.0, 2.0, 3.0])

# De esta manera obtendremos la suma de arreglos a y b
a + b



array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [75]:
# Matris transpuesta
print(x.T)
# try x.min(), x.max(), x.mean(), x.cumsum()


[[0.8794274  0.92523878 0.         0.         0.9577774 ]
 [0.         0.         0.         0.         0.90323881]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.98149701 0.        ]
 [0.         0.         0.         0.901075   0.        ]
 [0.         0.         0.         0.         0.        ]]


In [82]:
# La min(): función devuelve el elemento con el valor más bajo o el elemento con el valor más bajo en un iterable,
# en este caso  del arreglo

x.min()


0.0

In [79]:
# La función max(): La max()función devuelve el elemento con el valor más alto o el elemento con el valor más alto en un iterable,
# en este caso  del arreglo

x.max()


0.9814970130117243

In [80]:
# La función mean(): devuelve el promedio de los elementos de la matriz. El promedio se toma sobre la matriz aplanada por defecto, 
# de lo contrario sobre el eje especificado

x.mean()


0.1849418132839727

In [81]:
# La función cumsum(): devuelve la suma acumulativa de los elementos a lo largo de un eje dado.

x.cumsum()


array([0.8794274 , 0.8794274 , 0.8794274 , 0.8794274 , 0.8794274 ,
       0.8794274 , 1.80466618, 1.80466618, 1.80466618, 1.80466618,
       1.80466618, 1.80466618, 1.80466618, 1.80466618, 1.80466618,
       1.80466618, 1.80466618, 1.80466618, 1.80466618, 1.80466618,
       1.80466618, 2.78616319, 3.68723819, 3.68723819, 4.64501559,
       5.5482544 , 5.5482544 , 5.5482544 , 5.5482544 , 5.5482544 ])

In [84]:
# Multiplicamos la matriz por el valor de 5

print(x * 5)


[[4.39713701 0.         0.         0.         0.         0.        ]
 [4.62619389 0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         4.90748507 4.50537499 0.        ]
 [4.78888702 4.51619403 0.         0.         0.         0.        ]]


In [85]:
# Sumamos a la matriz el valor de 3 

print(x + 3)


[[3.8794274  3.         3.         3.         3.         3.        ]
 [3.92523878 3.         3.         3.         3.         3.        ]
 [3.         3.         3.         3.         3.         3.        ]
 [3.         3.         3.         3.98149701 3.901075   3.        ]
 [3.9577774  3.90323881 3.         3.         3.         3.        ]]


In [91]:
# x.T La matriz transpuesta.

print(x, x.T)

#  Producto de puntos de dos matrices.

print(np.dot(x, x.T))


[[0.8794274  0.         0.         0.         0.         0.        ]
 [0.92523878 0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.98149701 0.901075   0.        ]
 [0.9577774  0.90323881 0.         0.         0.         0.        ]] [[0.8794274  0.92523878 0.         0.         0.9577774 ]
 [0.         0.         0.         0.         0.90323881]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.98149701 0.        ]
 [0.         0.         0.         0.901075   0.        ]
 [0.         0.         0.         0.         0.        ]]
[[0.77339255 0.81368033 0.         0.         0.84229569]
 [0.81368033 0.85606679 0.         0.         0.88617279]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         1.77527254 0.        ]
 [0.84229569 0.88617279 0.         0.         1.7331779 ]]


In [92]:
# Para el cálculo del determinante y de la matriz inversa hay que acudir a una librería SciPy
from scipy import linalg

arr = np.array([[1, 2], [3,4]])

linalg.det(arr)


-2.0

In [93]:
# Las funciones de álgebra lineal de NumPy se basan en BLAS y LAPACK para proporcionar implementaciones eficientes
# de bajo nivel de algoritmos de álgebra lineal estándar. NumPy puede proporcionar esas bibliotecas utilizando versiones
# C de un subconjunto de sus implementaciones de referencia, pero, cuando sea posible, se prefieren las bibliotecas altamente
# optimizadas que aprovechan la funcionalidad del procesador especializado. Ejemplos de tales bibliotecas son OpenBLAS ,
# MKL (TM) y ATLAS. Debido a que esas bibliotecas son multiproceso y dependen del procesador, es posible que se necesiten 
# variables ambientales y paquetes externos como threadpoolctl para controlar el número de subprocesos
# o especificar la arquitectura del procesador.

print(linalg.inv(arr))


[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
print(b[0, 0])
print(b[-1, -1])
print(b[:, 1])

In [97]:
# Declaramos un arreglo genereado atravez de un for

a = np.array([[10*j+i for i in range(6)] for j in range(6)])


In [98]:
# Imprimimos el arreglo generado anteriormente

print(a)


[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [99]:
# Imprimimos el arreglo fila 0 con indice 3 al 5

print(a[0, 3:5])


[3 4]


In [100]:
#Imprimimos el arreglo fila 4 con indice del 4 en adelante

print(a[4:, 4:])


[[44 45]
 [54 55]]


In [101]:
# Imprimimos el arreglo columna 2 y sin limites (toda la columna)

print(a[:, 2])


[ 2 12 22 32 42 52]


In [102]:
# Imprimimos el arreglo columna 2 y sin limites (toda la columna)

print(a[2::2, ::2])


[[20 22 24]
 [40 42 44]]


In [104]:
# a la hora de copiar una matriz con todos sus atributos, se puede ejecutar la siguiente instrucción:

c = np.array(a, copy=True)

# Imprimimos el arreglo copiado

print(c)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
