# Trabajo con Numpy

In [2]:
# Importamos la librería de Numpy
import numpy as np

# Consultamos la version que tenemos instalada 
print('numpy version: ', np.__version__)

numpy version:  1.18.1


In [3]:
# Declaramos un arreglo

a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])

# Con valores numéricos del 0 al 11 en cada fila

rows, cols = np.shape(a)

print ('Rows:{0:03d} ; cols:{0:03d}'.format(rows, cols))

print(a)

Rows:003 ; cols:003
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Agregando valores complejos

In [7]:
# Declaramos un arreglo con números naturales
# Pero los convertimos en numero complejos

b = np.array([[1, 2], [9, 0], [4, 5]], dtype = np.complex64)

print ('Rows:{0:03d} ; cols:{0:03d}'.format(rows, cols))

print(b)

Rows:003 ; cols:003
[[1.+0.j 2.+0.j]
 [9.+0.j 0.+0.j]
 [4.+0.j 5.+0.j]]


### Inicializar vectores de dimensión 

In [15]:
# Inicializando un vector con variables inciales de 0 
np.zeros((4, 4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# Devuelve una matriz de ceros con la misma forma y tipo que una matriz determinada. 
np.zeros_like(b)


array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]], dtype=complex64)

In [14]:
# Devuelve una nueva matriz de formas y tipos dados, sin inicializar entradas.
np.empty((3, 3))


array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 6.66e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [17]:
# Devuelve una matriz 2-D con unos en la diagonal y ceros en otro lugar.
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
# np.diag(): Se utiliza esta función para extraer una diagonal y desea escribir en la matriz resultante; 
# si devuelve una copia o una vista depende de qué versión de numpy esté usando.

# np.arange(): Devuelve valores espaciados uniformemente dentro de un intervalo dado.
x = np.arange(5)

np.diag(x)


array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [25]:
# Devuelve valores espaciados uniformemente dentro de un intervalo dado.
np.arange(5)


array([0, 1, 2, 3, 4])

In [31]:
# np.tile(): Construye una matriz repitiendo A el número de veces dado por repeticiones.
x = np.array([[1, 0], [0, 1]])

np.tile(x, (2, 2))


array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [38]:
# np.arage(): Devuelve valores espaciados uniformemente dentro de un intervalo dado.
# np.reshape(): Da una nueva forma a una matriz sin cambiar sus datos.
x = np.arange(9).reshape(3, 3)

print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [44]:
# No es necesario especificar los valores del vector uno a uno, ta,bien es posible generarlos
b = np.array([[10*j+i for i in range(3)] for j in range(4)])

print(b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [49]:
# Añadir una nueva dimensión o convertir un vector fila en column

# np.linspace(): Devuelve números espaciados uniformemente en un intervalo especificado
# calculadas a lo largo del intervalo [ inicio , detención ],
# el punto final del intervalo puede excluirse opcionalmente.

d = np.linspace(0, 15, 6)

print(d)

print(d[:, np.newaxis])

[ 0.  3.  6.  9. 12. 15.]
[[ 0.]
 [ 3.]
 [ 6.]
 [ 9.]
 [12.]
 [15.]]


In [50]:
# np.mgrid(): devuelve una malla de malla densa (o desarrollada) cuando se indexa,
# de modo que cada argumento devuelto tiene la misma forma. 
# Las dimensiones y el número de las matrices de salida son iguales al número de dimensiones de indexación. 
# Si la longitud del paso no es un número complejo, entonces la parada no es inclusiva.

x, y = np.mgrid[0:5, 0:5] 

print(x)

print("---")

print(y)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
---
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [57]:
from scipy import sparse

# np.random.random(): devuelve flotaciones aleatorias en el intervalo medio abierto [0.0, 1.0).
# Los resultados son de la distribución "uniforme continuo" durante el intervalo establecido.
# Para muestrear Unif [a, b), b> a, multiplique la salida de random_samplepor (ba) y agregue a
# ( b  -  a )  *  random_sample ()  +  a

x = np.random.random((5, 6))

x[x < 0.85] = 0

print(x)

x_csr = sparse.csr_matrix(x)

print(x_csr)

[[0.8794274  0.         0.         0.         0.         0.        ]
 [0.92523878 0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.98149701 0.901075   0.        ]
 [0.9577774  0.90323881 0.         0.         0.         0.        ]]
  (0, 0)	0.879427401022772
  (1, 0)	0.9252387771426219
  (3, 3)	0.9814970130117243
  (3, 4)	0.9010749973495815
  (4, 0)	0.9577774040855614
  (4, 1)	0.9032388059069186


In [59]:
# toarray(): convertirá en un arreglo definido la enterior expresión
print(x_csr.toarray())


[[0.8794274  0.         0.         0.         0.         0.        ]
 [0.92523878 0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.98149701 0.901075   0.        ]
 [0.9577774  0.90323881 0.         0.         0.         0.        ]]


In [60]:
# Numpy permite la generación de número aleatorios en base a una semilla previamente especificada 
np.random.seed(12345)

np.random.rand(4, 5)


array([[0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503],
       [0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987],
       [0.74771481, 0.96130674, 0.0083883 , 0.10644438, 0.29870371],
       [0.65641118, 0.80981255, 0.87217591, 0.9646476 , 0.72368535]])

In [64]:
np.random.randn(4, 4)

array([[ 1.34974221,  0.06987669,  0.24667411, -0.0118616 ],
       [ 1.00481159,  1.32719461, -0.91926156, -1.54910644],
       [ 0.0221846 ,  0.75836315, -0.66052433,  0.86258008],
       [-0.0100319 ,  0.05000936,  0.67021559,  0.85296503]])

In [67]:
# De la siguiente forma podemos hacer una tranformación del tipo de valor que se encuentra dentro del arreglo
a = np.array([1,7, 1.2, 1.6])

b = a.astype(int)

b

array([1, 7, 1, 1])

In [71]:
# Realizamos un aproximación a los valores tipo fload del arreglo a
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5, 4.5])

b = np.around(a)

c = np.around(a).astype(int)

# El resultado será mostrado con los valores con tipo de dato entero
print(c)

[1 2 2 2 4 4 4]


In [74]:
# importamos la array de numpy
from numpy import array

# Declaramos 2 arreglos diferente dentro de 2 variables
a = array([1.0, 2.0, 3.0])

b = array([2.0, 2.0, 2.0])

a = b

from numpy import array

a = array([[0.0, 0.0, 0.0,],
           [10.0, 10.0, 10.0],
           [20.0, 20.0, 20.0],
           [30.0, 30.0, 30.0]])

b = array([1.0, 2.0, 3.0])

# De esta manera obtendremos la suma de arreglos a y b
a + b



array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [75]:
# Matris transpuesta
print(x.T)
# try x.min(), x.max(), x.mean(), x.cumsum()


[[0.8794274  0.92523878 0.         0.         0.9577774 ]
 [0.         0.         0.         0.         0.90323881]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.98149701 0.        ]
 [0.         0.         0.         0.901075   0.        ]
 [0.         0.         0.         0.         0.        ]]


In [82]:
# La min(): función devuelve el elemento con el valor más bajo o el elemento con el valor más bajo en un iterable,
# en este caso  del arreglo

x.min()


0.0

In [79]:
# La función max(): La max()función devuelve el elemento con el valor más alto o el elemento con el valor más alto en un iterable,
# en este caso  del arreglo

x.max()


0.9814970130117243

In [80]:
# La función mean(): devuelve el promedio de los elementos de la matriz. El promedio se toma sobre la matriz aplanada por defecto, 
# de lo contrario sobre el eje especificado

x.mean()


0.1849418132839727

In [81]:
# La función cumsum(): devuelve la suma acumulativa de los elementos a lo largo de un eje dado.

x.cumsum()


array([0.8794274 , 0.8794274 , 0.8794274 , 0.8794274 , 0.8794274 ,
       0.8794274 , 1.80466618, 1.80466618, 1.80466618, 1.80466618,
       1.80466618, 1.80466618, 1.80466618, 1.80466618, 1.80466618,
       1.80466618, 1.80466618, 1.80466618, 1.80466618, 1.80466618,
       1.80466618, 2.78616319, 3.68723819, 3.68723819, 4.64501559,
       5.5482544 , 5.5482544 , 5.5482544 , 5.5482544 , 5.5482544 ])

In [84]:
# Multiplicamos la matriz por el valor de 5

print(x * 5)


[[4.39713701 0.         0.         0.         0.         0.        ]
 [4.62619389 0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         4.90748507 4.50537499 0.        ]
 [4.78888702 4.51619403 0.         0.         0.         0.        ]]


In [85]:
# Sumamos a la matriz el valor de 3 

print(x + 3)


[[3.8794274  3.         3.         3.         3.         3.        ]
 [3.92523878 3.         3.         3.         3.         3.        ]
 [3.         3.         3.         3.         3.         3.        ]
 [3.         3.         3.         3.98149701 3.901075   3.        ]
 [3.9577774  3.90323881 3.         3.         3.         3.        ]]


In [91]:
# x.T La matriz transpuesta.

print(x, x.T)

#  Producto de puntos de dos matrices.

print(np.dot(x, x.T))


[[0.8794274  0.         0.         0.         0.         0.        ]
 [0.92523878 0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.98149701 0.901075   0.        ]
 [0.9577774  0.90323881 0.         0.         0.         0.        ]] [[0.8794274  0.92523878 0.         0.         0.9577774 ]
 [0.         0.         0.         0.         0.90323881]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.98149701 0.        ]
 [0.         0.         0.         0.901075   0.        ]
 [0.         0.         0.         0.         0.        ]]
[[0.77339255 0.81368033 0.         0.         0.84229569]
 [0.81368033 0.85606679 0.         0.         0.88617279]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         1.77527254 0.        ]
 [0.84229569 0.88617279 0.         0.         1.7331779 ]]


In [92]:
# Para el cálculo del determinante y de la matriz inversa hay que acudir a una librería SciPy
from scipy import linalg

arr = np.array([[1, 2], [3,4]])

linalg.det(arr)


-2.0

In [93]:
# Las funciones de álgebra lineal de NumPy se basan en BLAS y LAPACK para proporcionar implementaciones eficientes
# de bajo nivel de algoritmos de álgebra lineal estándar. NumPy puede proporcionar esas bibliotecas utilizando versiones
# C de un subconjunto de sus implementaciones de referencia, pero, cuando sea posible, se prefieren las bibliotecas altamente
# optimizadas que aprovechan la funcionalidad del procesador especializado. Ejemplos de tales bibliotecas son OpenBLAS ,
# MKL (TM) y ATLAS. Debido a que esas bibliotecas son multiproceso y dependen del procesador, es posible que se necesiten 
# variables ambientales y paquetes externos como threadpoolctl para controlar el número de subprocesos
# o especificar la arquitectura del procesador.

print(linalg.inv(arr))


[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
print(b[0, 0])
print(b[-1, -1])
print(b[:, 1])

In [97]:
# Declaramos un arreglo genereado atravez de un for

a = np.array([[10*j+i for i in range(6)] for j in range(6)])


In [98]:
# Imprimimos el arreglo generado anteriormente

print(a)


[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [99]:
# Imprimimos el arreglo fila 0 con indice 3 al 5

print(a[0, 3:5])


[3 4]


In [100]:
#Imprimimos el arreglo fila 4 con indice del 4 en adelante

print(a[4:, 4:])


[[44 45]
 [54 55]]


In [101]:
# Imprimimos el arreglo columna 2 y sin limites (toda la columna)

print(a[:, 2])


[ 2 12 22 32 42 52]


In [102]:
# Imprimimos el arreglo columna 2 y sin limites (toda la columna)

print(a[2::2, ::2])


[[20 22 24]
 [40 42 44]]


In [104]:
# a la hora de copiar una matriz con todos sus atributos, se puede ejecutar la siguiente instrucción:

c = np.array(a, copy=True)

# Imprimimos el arreglo copiado

print(c)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


# Trabajando con Pandas

In [11]:
# es muy importante a la hora de trabajar con pandas hacer la respectiva importación 
import pandas as pd
import numpy as np

# Declarando un objeto de la calse pandas 
s = pd.Series([1, 3, 5, np.nan, 6, 8])

s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [15]:
# pd.date_range(): evuelve una frecuencia fija DatetimeIndex

dates = pd.date_range('20200101', periods = 6)

dates

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')

In [18]:
# Datos tabulares bidimensionales, de tamaño variable y potencialmente heterogéneos.

# La estructura de datos también contiene ejes etiquetados (filas y columnas). 
# Las operaciones aritméticas se alinean en las etiquetas de fila y columna.
# Puede considerarse como un contenedor tipo dict para objetos de la serie.
# La estructura de datos primaria de los pandas.

df = pd.DataFrame(np.random.randn(6, 4), index = dates, columns = list('ABCD'))

df

A         B         C         D
2020-01-01 -1.301049  1.200909 -1.206538 -0.190326
2020-01-02  1.441891 -0.670338 -0.480695  2.324189
2020-01-03  2.094697 -1.630105  1.049553  0.816077
2020-01-04 -0.312574 -0.191367 -0.425907  1.487474
2020-01-05 -1.334538  1.317744 -1.553607  0.980485
2020-01-06  0.229658 -1.290763 -0.700799 -0.428626

In [29]:
# Datos tabulares bidimensionales, de tamaño variable y potencialmente heterogéneos.
# El sisguiente es un ejemplo de un dataFrame con tipos de datos variados

df2 = pd.DataFrame({'A': 1.,
                    'B':pd.Timestamp('20200102'),
                    'C':pd.Series(1, index = list(range(4)), dtype = 'float32'),
                    'D':np.array([3] * 4, dtype = 'int32'),
                    'E':pd.Categorical(["aprobado", "rechazado", "aprobado", "rechazado"]),
                    'F':'completado'})
df2

A          B    C  D          E           F
0  1.0 2020-01-02  1.0  3   aprobado  completado
1  1.0 2020-01-02  1.0  3  rechazado  completado
2  1.0 2020-01-02  1.0  3   aprobado  completado
3  1.0 2020-01-02  1.0  3  rechazado  completado

In [30]:
# A continuación se muestran diversas funciones útiles para acceder a las características de un DataFrame

df.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')

In [32]:
# Las etiquetas de columna del DataFrame.

df.columns


Index(['A', 'B', 'C', 'D'], dtype='object')

In [33]:
# Solo se devolverán los valores en el DataFrame, se eliminarán las etiquetas de los ejes.

df.values


array([[-1.30104869,  1.20090941, -1.20653846, -0.1903258 ],
       [ 1.44189085, -0.67033834, -0.48069479,  2.32418857],
       [ 2.09469668, -1.63010476,  1.04955349,  0.8160767 ],
       [-0.31257427, -0.19136707, -0.42590746,  1.4874738 ],
       [-1.33453784,  1.31774364, -1.55360725,  0.98048536],
       [ 0.22965835, -1.29076315, -0.70079928, -0.42862604]])

In [35]:
# Generar estadísticas descriptivas.
# Las estadísticas descriptivas incluyen aquellas que resumen la tendencia central, 
# la dispersión y la forma de la distribución de un conjunto de datos, excluyendo los NaNvalores.

df.describe()


A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.136348 -0.210653 -0.552999  0.831545
std    1.412758  1.242712  0.898858  1.030815
min   -1.334538 -1.630105 -1.553607 -0.428626
25%   -1.053930 -1.135657 -1.080104  0.061275
50%   -0.041458 -0.430853 -0.590747  0.898281
75%    1.138833  0.852840 -0.439604  1.360727
max    2.094697  1.317744  1.049553  2.324189

In [36]:
# Realizar la transposición del DataFrame y ordenar son algunas de las funcionalidades más recurrentes:

df.T

2020-01-01  2020-01-02  2020-01-03  2020-01-04  2020-01-05  2020-01-06
A   -1.301049    1.441891    2.094697   -0.312574   -1.334538    0.229658
B    1.200909   -0.670338   -1.630105   -0.191367    1.317744   -1.290763
C   -1.206538   -0.480695    1.049553   -0.425907   -1.553607   -0.700799
D   -0.190326    2.324189    0.816077    1.487474    0.980485   -0.428626

In [37]:
# Ordenar objetos por etiquetas (a lo largo de un eje).

df.sort_index(axis = 1, ascending = False)


D         C         B         A
2020-01-01 -0.190326 -1.206538  1.200909 -1.301049
2020-01-02  2.324189 -0.480695 -0.670338  1.441891
2020-01-03  0.816077  1.049553 -1.630105  2.094697
2020-01-04  1.487474 -0.425907 -0.191367 -0.312574
2020-01-05  0.980485 -1.553607  1.317744 -1.334538
2020-01-06 -0.428626 -0.700799 -1.290763  0.229658

In [39]:
# El acceso a los datos guarda similtudes con lo visto con la librería Numpy. Las funciones head() y tail()
# nos proporcionan una visión de los datos de cabeza y del final de la estructura.

df.head()


A         B         C         D
2020-01-01 -1.301049  1.200909 -1.206538 -0.190326
2020-01-02  1.441891 -0.670338 -0.480695  2.324189
2020-01-03  2.094697 -1.630105  1.049553  0.816077
2020-01-04 -0.312574 -0.191367 -0.425907  1.487474
2020-01-05 -1.334538  1.317744 -1.553607  0.980485

In [40]:
df.tail(3)

A         B         C         D
2020-01-04 -0.312574 -0.191367 -0.425907  1.487474
2020-01-05 -1.334538  1.317744 -1.553607  0.980485
2020-01-06  0.229658 -1.290763 -0.700799 -0.428626

In [41]:
# Para acceder a los valores individuales por columna, fila,
# rango de columnas o filas hay varias opciones disponibles que se muestren
# en los ejemplos siguientes.

df['A']

2020-01-01   -1.301049
2020-01-02    1.441891
2020-01-03    2.094697
2020-01-04   -0.312574
2020-01-05   -1.334538
2020-01-06    0.229658
Freq: D, Name: A, dtype: float64

In [42]:
# Especificando el inicio y el fin de las filas

df[0:3]


A         B         C         D
2020-01-01 -1.301049  1.200909 -1.206538 -0.190326
2020-01-02  1.441891 -0.670338 -0.480695  2.324189
2020-01-03  2.094697 -1.630105  1.049553  0.816077

In [43]:
# Especificando las finals y columnas acorde a los datos presentes dentro del arreglo 

df['20200102' : '20200104']

A         B         C         D
2020-01-02  1.441891 -0.670338 -0.480695  2.324189
2020-01-03  2.094697 -1.630105  1.049553  0.816077
2020-01-04 -0.312574 -0.191367 -0.425907  1.487474

In [47]:
# Si queremos realizar una selección a través del índice deberemos emplear la función .loc()

df.loc(dates[1])


In [ ]:
df.loc[:, 'A', 'B']

In [49]:
# Tambíen tenemos la opción de filtrar y seleccionar únicamente los valores que
# cumplan unadeterminada condición.

df[df.A > 0]


A         B         C         D
2020-01-02  1.441891 -0.670338 -0.480695  2.324189
2020-01-03  2.094697 -1.630105  1.049553  0.816077
2020-01-06  0.229658 -1.290763 -0.700799 -0.428626

In [51]:
df[df > 0]

A         B         C         D
2020-01-01       NaN  1.200909       NaN       NaN
2020-01-02  1.441891       NaN       NaN  2.324189
2020-01-03  2.094697       NaN  1.049553  0.816077
2020-01-04       NaN       NaN       NaN  1.487474
2020-01-05       NaN  1.317744       NaN  0.980485
2020-01-06  0.229658       NaN       NaN       NaN

In [62]:
# Similar al lenguaje SQL podemos unir 2 DataFrames en este caso mediante la función join()

left = pd.DataFrame({'key': ['completado', 'completado'], 'completado': [1, 2]})

left

key  completado
0  completado           1
1  completado           2

In [64]:
right = pd.DataFrame({'key': ['completado', 'completado'], 'rval': [4, 5]})
, ''
right

key  rval
0  completado     4
1  completado     5

In [67]:
pd.merge(left, right, on = 'key')

key  completado  rval
0  completado           1     4
1  completado           1     5
2  completado           2     4
3  completado           2     5

In [70]:
# También tenemos la posiblidad de ejecutar funciones de agrupación al estilo de SQL
# como se muestra en el siguiente ejemplo

df = pd.DataFrame({'A': ['completado', 'aceptado', 'completado', 'aceptado', 'completado', 'aceptado', 'completado', 'completado'],
                   'B': ['uno', 'uno', 'dos', 'tres', 'dos', 'dos', 'uno', 'tres'],
                   'C': np.random.randn(8),
                   'D': np.random.randn(8)})

In [71]:
df

A     B         C         D
0  completado   uno -0.131653 -0.716538
1    aceptado   uno -0.557614  1.321956
2  completado   dos  0.209291 -0.385098
3    aceptado  tres -1.310820  0.251172
4  completado   dos  0.800520 -0.388496
5    aceptado   dos -0.167362 -0.933169
6  completado   uno  0.393326 -2.209292
7  completado  tres  0.217880  0.191239

In [73]:
# Agrupe DataFrame usando un mapeador o por una serie de columnas.

# Una operación groupby implica una combinación de dividir el objeto, aplicar una función y 
# combinar los resultados. Esto se puede usar para agrupar grandes cantidades de datos 
# y operaciones de cálculo en estos grupos.

df.groupby('A').sum()

C         D
A                             
aceptado   -2.035796  0.639960
completado  1.489364 -3.508184