# Trabajo con Numpy

In [2]:
# Importamos la librería de Numpy
import numpy as np

# Consultamos la version que tenemos instalada 
print('numpy version: ', np.__version__)

numpy version:  1.18.1


In [3]:
# Declaramos un arreglo

a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])

# Con valores numéricos del 0 al 11 en cada fila

rows, cols = np.shape(a)

print ('Rows:{0:03d} ; cols:{0:03d}'.format(rows, cols))

print(a)

Rows:003 ; cols:003
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Agregando valores complejos

In [7]:
# Declaramos un arreglo con números naturales
# Pero los convertimos en numero complejos

b = np.array([[1, 2], [9, 0], [4, 5]], dtype = np.complex64)

print ('Rows:{0:03d} ; cols:{0:03d}'.format(rows, cols))

print(b)

Rows:003 ; cols:003
[[1.+0.j 2.+0.j]
 [9.+0.j 0.+0.j]
 [4.+0.j 5.+0.j]]


### Inicializar vectores de dimensión 

In [15]:
# Inicializando un vector con variables inciales de 0 
np.zeros((4, 4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# Devuelve una matriz de ceros con la misma forma y tipo que una matriz determinada. 
np.zeros_like(b)


array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]], dtype=complex64)

In [14]:
# Devuelve una nueva matriz de formas y tipos dados, sin inicializar entradas.
np.empty((3, 3))


array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 6.66e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [17]:
# Devuelve una matriz 2-D con unos en la diagonal y ceros en otro lugar.
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
# np.diag(): Se utiliza esta función para extraer una diagonal y desea escribir en la matriz resultante; 
# si devuelve una copia o una vista depende de qué versión de numpy esté usando.

# np.arange(): Devuelve valores espaciados uniformemente dentro de un intervalo dado.
x = np.arange(5)

np.diag(x)


array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [25]:
# Devuelve valores espaciados uniformemente dentro de un intervalo dado.
np.arange(5)


array([0, 1, 2, 3, 4])

In [31]:
# np.tile(): Construye una matriz repitiendo A el número de veces dado por repeticiones.
x = np.array([[1, 0], [0, 1]])

np.tile(x, (2, 2))


array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [38]:
# np.arage(): Devuelve valores espaciados uniformemente dentro de un intervalo dado.
# np.reshape(): Da una nueva forma a una matriz sin cambiar sus datos.
x = np.arange(9).reshape(3, 3)

print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [44]:
# No es necesario especificar los valores del vector uno a uno, ta,bien es posible generarlos
b = np.array([[10*j+i for i in range(3)] for j in range(4)])

print(b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [49]:
# Añadir una nueva dimensión o convertir un vector fila en column

# np.linspace(): Devuelve números espaciados uniformemente en un intervalo especificado
# calculadas a lo largo del intervalo [ inicio , detención ],
# el punto final del intervalo puede excluirse opcionalmente.

d = np.linspace(0, 15, 6)

print(d)

print(d[:, np.newaxis])

[ 0.  3.  6.  9. 12. 15.]
[[ 0.]
 [ 3.]
 [ 6.]
 [ 9.]
 [12.]
 [15.]]
